config/routes.rb
Rails.application.routes.draw do
  #root to: 'home#index'
  root to: 'users#new'
  delete "log_out" => "sessions#destroy", :as => "log_out"
  resources :users
  resources :sessions,only: [:new,:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save :encrypt_password
  
  #validates_confirmation_of :password
  #validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :user_logged_in?
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def authenticate!
    unless current_user.present?
      redirect_to root_path, alert: "Please login first."
    end
  end
  
  def user_logged_in?
    current_user.present?
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_path, :notice => "Logged in!"
    else
      flash[:error] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit,:update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(allowed_user_params)
    if @user.save
      #flash[:notice] = "User created successfully."
      redirect_to edit_user_path(@user)
    else
      flash[:error] = @user.errors.full_messages.join(',')
      render :new
    end
  end
  
  def edit
    
  end
  
  def update
    if @user.update(allowed_user_params)
      flash[:notice] = "Signed up successfully."
      redirect_to root_path
    else
      flash[:error] = @user.errors.full_messages.join(',')
      render :edit
    end
  end
  
  private
  
  def set_user
    @user = User.find params[:id]
  end
  
  def allowed_user_params
    params.require(:user).permit!
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%if user_logged_in?%>
  <%= link_to "Log Out",log_out_path,:method=>"delete" %>
<%else%>
  <%= link_to "Login", new_session_path %>
  <%= link_to "Register", new_user_path %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestJob</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Neuton:400,800" rel="stylesheet">
  </head>

  <body style="font-size: <%= controller.action_name == 'edit' ? '2rem;' : '1rem;' %>">
    <%= render partial: "/messages"%>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <label>Email</label>
  <%= f.email_field :email,:required=> true,:autofocus=>true %>
  <label>Password</label>
  <%= f.password_field :password,:required=> true %>
  <label>Password Confirmation</label>
  <%= f.password_field :password_confirmation,:required=> true %>
  <%= f.submit  %>
<%end%>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <a hrf="users/new">
        <%= image_tag 'logo.jpg' %>
      </a>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="login-form mt-5">
        <h1>Just a few quick thing to set up your account...</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <label>Full name</label>
            <%= f.text_field :name,:class=>"form-control validate[required,custom[fullname]]",:placeholder=>"Full name" %>
          </div>
          <div class="form-group">
            <label>Password</label>
            <%= f.password_field :password,:class=>"form-control validate[required,custom[password],custom[password_length]",:placeholder=>"Password" %>
            <hr>
            <p class="form-text text-muted">Passwords must be at least 6 characters long and can’t be the like "password", "123456" or "abcdef"</p>
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-success text-center">Ready! <i class="fa fa-arrow-right"></i></button>
          </div>
        <%end%>   
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <a hrf="#">
        <%= image_tag "logo.jpg" %>
      </a>
    </div>
    <div class="col-6 text-right">
      <%= link_to "Sign in", new_session_path %>
    </div>
  </div>

  <div class="contant-block row mt-5">
    <div class="left-image col-md-6">
      <%= image_tag "home_illo.png" %>
    </div>
    <div class="text-contant-right col-md-6">
      <h1>Where Work Happens</h1>
      <p>When your team needs to kick off a project, hire a new employee, deploy some code, review a sales contract, finalize next year's budget, measure an A/B test, plan your next office opening, and more, Slack has you covered.</p>
      <%= form_for @user,:html=>{:class=>"form-inline seach-from"} do |f| %>
        <label class="sr-only" for="inlineFormInputName2">Name</label>
        <%= f.email_field :email,:class=>"form-control mb-2 mr-sm-2 validate[required,custom[email]]",:placeholder=>"Email address" %>
        <%= f.submit "Get Started",:class=>"btn btn-success mb-2 pl-3  pr-3"%>
      <%end%>
      <p class="account mt-2">Already using Slack? <%= link_to "Sign in", new_session_path %></p>
    </div>  
  </div>
</div>